### ISSUE TITLE
Support plan for Ecoinvent 3.8?

### ISSUE THREAD

**Issue by complexly** [MaximeAgez/pylcaio#3]
First, thank you for sharing this brillient work!
Is there a plan to update the package and support the new Ecoinvent 3.8 database? Thanks!

**Comment by MaximeAgez** [comment]
Hi @complexly. Thanks for your interest :) Support for ecoinvent3.8 will be added early 2022. It takes some time to parse ecoinvent3.8 in Python + develop necessary concordance between new processes and exiobase sectors.
